export const USER_FETCH_DATA_LOADING = "USER_FETCH_DATA_LOADING";
export const USER_FETCH_DATA_SUCCESS = "USER_FETCH_DATA_SUCCESS";
export const USER_FETCH_DATA_FAIL = "USER_FETCH_DATA_FAIL";

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SET_AUTHORIZATION = "SET_AUTHORIZATION";
export const LOG_OUT_BEGIN = "LOG_OUT_BEGIN";
export const LOG_OUT_END = "LOG_OUT_END";

export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAIL = "UPLOAD_FAIL";
export const FETCH_IMAGES_SUCCESS = "FETCH_IMAGES_SUCCESS";
export const FETCH_IMAGES_FAIL = "FETCH_IMAGES_FAIL";
export const FETCH_PICTURE_SUCCESS = "FETCH_PICTURE_SUCCESS";
export const FETCH_PICTURE_FAIL = "FETCH_PICTURE_FAIL";
